name: App A
on:
  workflow_dispatch:
  workflow_call:
    
env:
  BUILD_CONFIGURATION: 'Release'

permissions:
  id-token: write # requesting JWT in migration workflows for oidc auth with Azure
  contents: read # required for actions/checkout
  statuses: write # required for dorny/test-reporter
  checks: write # required for dorny/test-reporter

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install .NET Core 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Projects
        run: dotnet restore AppA/MonoRepo.AppA/MonoRepo.AppA.csproj

      - name: Build
        run: dotnet build AppA/MonoRepo.AppA/MonoRepo.AppA.csproj --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
      
        
  Test:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v3

      - name: Install .NET Core 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Projects
        run: dotnet restore AppA/MonoRepo.AppA.Tests/MonoRepo.AppA.Tests.csproj

      - name: Build
        run: dotnet build AppA/MonoRepo.AppA.Tests/MonoRepo.AppA.Tests.csproj --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Tests
        run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} AppA/MonoRepo.AppA.Tests/MonoRepo.AppA.Tests.csproj
        
  AppAStatusCheck:
    runs-on: ubuntu-latest
    if: always()
    needs: [Build, Test]
    steps:
      - run: echo "App A passed"